### ISSUE TITLE
can I skip some steps when analyzing centroided data

### ISSUE THREAD

**Issue by Haoran-pumc** [sgibb/MALDIquant#79]
I have noticed that MALTIquant encounters issues with smoothing and removing the baseline when processing centroided data. However, if I do not centroid the data, I will have 30 data files, each 30 MB in size, which would take too long to load. Can I use Bruker's data analysis software to filter for SNR and absolute intensity, thereby obtaining a smaller file input, and then skip the steps of smoothing and removing the baseline?

**Comment by sgibb** [comment]
Short answer: of course you could skip each step in `MALDIquant`.
But:
I would not use the bruker software for anything else than converting the raw data to mzML (because of its blackbox nature). I especially recommend against filtering some intensities (not even zero ones). This would result in irregular sized steps between each data point and all window-based operations (smoothing, baseline correction, peak detection) could produce unexpected results (because of irregular window size). However, if you decide to do the whole preprocessing (smoothing, baseline correction, normalisation, peak detection, filtering) in the bruker software you could import these data in MALDIquant as centroided data and work with the generated `MassPeaks` objects. `MALDIquantForeign::import` should automatically generate the correct objects for you. Subsequently you could align and bin your peaks for further analysis.

**Comment by Haoran-pumc** [comment]
Thank you very much! I ultimately chose to use non-centroided data to obtain more accurate results!
